# Generated by Django 6.0.5 on 2026-05-19 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('arenas', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arenaparticipant',
            name='current_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matches.match'),
        ),
        migrations.AddField(
            model_name='arenaparticipant',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.guestparticipant'),
        ),
        migrations.AddField(
            model_name='arenaparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arenascore',
            name='arena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='arenas.arena'),
        ),
        migrations.AddField(
            model_name='arenascore',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='arenas.arenaparticipant'),
        ),
        migrations.AlterUniqueTogether(
            name='arenaparticipant',
            unique_together={('arena', 'guest'), ('arena', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='arenascore',
            unique_together={('arena', 'participant')},
        ),
    ]
